"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ts_mongoose_1 = require("ts-mongoose");
exports.SiteObject = {
    _id: ts_mongoose_1.Type.optionalString({ required: true }),
    clientId: ts_mongoose_1.Type.optionalString({ required: true }),
    autoGenerated: ts_mongoose_1.Type.optionalBoolean(),
    title: ts_mongoose_1.Type.optionalString(),
    UPRN: ts_mongoose_1.Type.string({ required: true }),
    UPRNLabel: ts_mongoose_1.Type.string({ required: true }),
    postcode: ts_mongoose_1.Type.string({ required: true }),
    addressLine1: ts_mongoose_1.Type.string({ required: true }),
    city: ts_mongoose_1.Type.string({ required: true }),
    county: ts_mongoose_1.Type.string({ required: true }),
    mandatoryInduction: ts_mongoose_1.Type.boolean({ required: true }),
    createdAt: ts_mongoose_1.Type.optionalDate({
        required: true,
        default: new Date(Date.now())
    }),
    teamsId: ts_mongoose_1.Type.optionalString()
};
var SiteSchema = ts_mongoose_1.createSchema(exports.SiteObject);
exports.Site = ts_mongoose_1.typedModel('sites', SiteSchema);
